### ISSUE TITLE
still not found

### ISSUE THREAD

**Issue by sysdl132** [SheepTester/platformre#25]
I just reported this problem few days ago.But now after submit,the formspree page is gone(reCAPTCHA),the final link still is
https://sheeptester.github.io/platformre **/platformre** /gotit.html
it isn't fixed.
![img1](https://user-images.githubusercontent.com/54708046/75315486-d2533680-589d-11ea-8222-88792f78cac9.png)
The correct page should be:
https://sheeptester.github.io/platformre/gotit.html
![img2](https://user-images.githubusercontent.com/54708046/75315536-f0209b80-589d-11ea-92d3-1b9db0d193b6.png)

**Comment by sysdl132** [comment]
@SheepTester 
I have a solution:
![solution](https://user-images.githubusercontent.com/54708046/75315855-cae05d00-589e-11ea-9f19-e46231b2087e.png)
Erase the "platformre" before "gotit.html".
(This file is from:submit.html line 85)

**Comment by SheepTester** [comment]
Thanks for the report; I just fixed it in 0e6a7821e5a9f4798d7798c6f00dd9a6ab9f3456

For some reason I'm not receiving notifications from issues on my repositories?
