### ISSUE TITLE
Restarting Issue

### ISSUE THREAD

**Issue by gazalied** [SheepTester/platformre#27]
If you run into a spike or lava, you have a red circle and you can hardly move. If you restart, the player will still have the red circle but it can move normally.

**Comment by SheepTester** [comment]
![THE GIF](https://user-images.githubusercontent.com/22133785/112925255-6ce7ff80-90c6-11eb-8cca-4f025e5664ed.gif)

I can't reproduce

**Comment by SheepTester** [comment]
If you're talking about A Platformer, the player's dot turning red and being slow for a moment after death is intentional; it matches the behaviour of [the original](https://scratch.mit.edu/projects/67794652/)

**Comment by gazalied** [comment]
> ![THE GIF](https://user-images.githubusercontent.com/22133785/112925255-6ce7ff80-90c6-11eb-8cca-4f025e5664ed.gif)
> 
> I can't reproduce

The other one




https://user-images.githubusercontent.com/76770572/112976963-b47e9200-917f-11eb-9e15-8f5a268f07f1.mp4

**Comment by SheepTester** [comment]
Ah,

> If you run into a spike or lava, you have a red circle and you can hardly move.

This is intentional as a slight fee for dying. However,

> If you restart, the player will still have the red circle but it can move normally.

I'm not sure if this is meant to match the original Scratch project; I'll investigate

**Comment by SheepTester** [comment]
Okay, it seems that the original project didn't reset the timer or anything when you restart, but the red dot stays and goes away as scheduled.
