### ISSUE TITLE
Insect spotted on highway 28

### ISSUE THREAD

**Issue by ghost** [SheepTester/platformre#28]
If you stand on the edge of the rage powerup hitbox, activate it, and then run into a block at the bottom left corner block, must be solid, (width 35, height 19) you will move through it with no way back.
Level Code to test bug:
```[[{"cpx":80,"cpy":80},"Hello world!"],"v@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@v","@                                +@","@                           vvvvvv@","@                                 @","@                                 @","@                                 @","@                                 @","@                                 @","@                                 @","@             @@@                 @","@        @@@C;@i@                 @","@                                 @","@                                 @","@                                 @","@                                 @","@                                 @","@                                 @","@                                 @","v@@@@o@@@@@@@@@@@@@@@@@@@@@@@@@@@@v"]```

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/64666021/114222835-ecc26500-9923-11eb-8ba2-f8114fcd6e75.png)
Don't forget that s t i c k y b l o c k

**Comment by ghost** [comment]
Another bug with the physics is that you can't move in the air which is stupid

**Comment by SheepTester** [comment]
I did some playtesting in Outside and found that I was unable to move horizontally while in the air

**Comment by SheepTester** [comment]
I am able to reproduce the bug:

```json
[[{"cpx":187,"cpy":80},"Hello world!"],"@@@@@@@","@     @","@     @","@     @","@     @","@     @","@@@@@o@"]
```

However, I probably won't fix it as this project is old and is only here for historical reasons; also, I think the rage effect or whatever was buggy (perhaps intentionally so 🍋).

> Another bug with the physics is that you can't move in the air which is stupid

This isn't a bug
